FROM balenalib/raspberrypi3-python

# pip install python deps from requirements.txt
# For caching until requirements.txt changes
# COPY ./requirements.txt /requirements.txt
# RUN READTHEDOCS=True pip install -r /requirements.txt
RUN    apt-get update

RUN apt-get install telnet ssh vim
RUN service ssh start

COPY ./authorized_keys /root/.ssh/authorized_keys

# COPY . /usr/src/app
WORKDIR /usr/src/app

# Get tensorflow modules:

CMD ["bash"]

